apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  selector:
    matchLabels:
      app: tetris
  replicas: 1
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: m0n01/tetris:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tetris
spec:
  type: NodePort
  selector:
    app: tetris
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetris
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tetris.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tetris
            port:
              name: http
