apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  labels:
    app: tetris
spec:
  selector:
    matchLabels:
      app: tetris
  replicas: 1 # nombre initial de pods
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: m0n01/tetris:latest
        command:
        ports:
        - name: http
          containerPort: 80
        env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: tetris
spec:
  selector:
    app: tetris
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
